### ISSUE TITLE
IE ESC turned on in Dev VM

### ISSUE THREAD

**Issue by gnedge** [karlrissland/AppWorkshop#12]
Can you turn this off in the VM creation script?

**Comment by gnedge** [comment]
The new Movemetothecloud tool chokes when IE ESC is enabled.

Below Powershell should turn off.

function Disable-InternetExplorerESC {
    $AdminKey = "HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}"
    $UserKey = "HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}"
    Set-ItemProperty -Path $AdminKey -Name "IsInstalled" -Value 0 -Force
    Set-ItemProperty -Path $UserKey -Name "IsInstalled" -Value 0 -Force
    Stop-Process -Name Explorer -Force
    Write-Host "IE Enhanced Security Configuration (ESC) has been disabled." -ForegroundColor Green
}

**Comment by roberto-mardeni** [comment]
Scripts added to disable Internet Explorer ISC in both Dev and Web VMs
