### ISSUE TITLE
Deploying on VS Community Edition the DB Project Fails to Load

### ISSUE THREAD

**Issue by thekwilson** [karlrissland/AppWorkshop#4]
If you choose the VS Community Edition option in the ARM template you end up with errors when you open the solution.  The errors happen on the load of the DB project and it is because the ReadyRoll extension is not present in VS Community Edition.  To resolve manually you have to install the ReadyRoll VS Extension and re-start VS.

**Comment by roberto-mardeni** [comment]
This will likely be fixed by using the VS Community Edition and installing ReadyRoll via script to have it available before the build happens.

**Comment by roberto-mardeni** [comment]
This was already resolved
